### ISSUE TITLE
Use Python for the backend

### ISSUE THREAD

**Issue by gadomski** [gadomski/heystac#23]
While I enjoy the fact that this project is spurring on additional development in **stac-rs**, it's reached the point where I'm being slowed down. As I [told myself](https://www.gadom.ski/posts/rust-and-geospatial/#use-rust-for-geo-adjacent-not-geo-native):

> If you're doing "geo-native" work where you're opening lots of files, doing analysis, creating visualizations, stick to Python.

Especially as I iterate on [ratings](https://github.com/radiantearth/stac-spec/discussions/1328), I'll want a quick-moving implementation that other people can audit. That means 🐍 > 🦀.

**Comment by ircwaves** [comment]
_Lingua franca_ ftw  `¯\_ (ツ)_/¯`

**Comment by gadomski** [comment]
Right?

Also the reimplmentation took like fifteen minutes, so 🚤
